### PR TITLE
Remove ListenerFileUserStoreBasicAuthHandler and parameterize the PoolConfiguration

### PR DESCRIPTION
**Pull request by BuddhiWathsala**
## Purpose
$subject

## Approach
- Remove ListenerFileUserStoreBasicAuthHandler
- Parameterize the PoolConfiguration

## Related PRs
- https://github.com/ballerina-platform/module-ballerina-grpc/pull/83
- https://github.com/ballerina-platform/module-ballerina-grpc/pull/74

## Test environment
- macOS
- SLP9
- Java11

### CODE REVIEW

**Comment by HindujaB** [comment]
Do we have any tests that use the basic authentication?

**Comment by HindujaB** [comment]
And if we remove the config API dependency with this changes, shall we remove the gradle files and properties related to this?
Eg: service_config.conf, the command line argument we use to pass this config file

**Comment by BuddhiWathsala** [comment]
> Do we have any tests that use the basic authentication?

There is no other test to cover basic auth tests ATM.

**Comment by ldclakmal** [comment]
@BuddhiWathsala I think we should remove the `--b7a.config.file=....` part of these commands as well.
https://github.com/ballerina-platform/module-ballerina-grpc/blob/master/grpc-ballerina/build.gradle#L225

**Comment by BuddhiWathsala** [comment]
> @BuddhiWathsala I think we should remove the `--b7a.config.file=....` part of these commands as well.
> https://github.com/ballerina-platform/module-ballerina-grpc/blob/master/grpc-ballerina/build.gradle#L225

Fixed in here https://github.com/ballerina-platform/module-ballerina-grpc/pull/87/commits/0164a6f7035838dc3e8f92981653c96e29fedb3b

**Review by ldclakmal — APPROVED** [review]

**Review by daneshk — APPROVED** [review]

**Pull request merged**
