### PR TITLE
Reduce RPS in load tests

### PR DESCRIPTION
**Pull request by dilanSachi**
## Purpose
$subject
This is to test about the minor error rate appearing in the load test results
## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests

### CODE REVIEW

**Comment by BuddhiWathsala** [comment]
@dilanSachi, can we see a log that belongs to this error?

**Comment by dilanSachi** [comment]
> @dilanSachi, can we see a log that belongs to this error?

unfortunately no. if the logs are written to a file, the file becomes too large and its hard to process the file

**Review by BuddhiWathsala — APPROVED** [review]

**Comment by BuddhiWathsala** [comment]
Better if we could see what is the cause.

**Comment by dilanSachi** [comment]
> Better if we could see what is the cause.

will try to find a way to stdout the error. since we dont have access to the pods

**Pull request merged**
