### PR TITLE
Add client error sending functionality in client/bidirectional streaming scenarios

### PR DESCRIPTION
**Pull request by dilanSachi**
## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [x] Added tests

Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/386

### CODE REVIEW

**Review by daneshk — DISMISSED** [review]
LGTM

**Review by BuddhiWathsala — DISMISSED** [review]

**Comment by dilanSachi** [comment]
Seems like closing the stream does not work as expected(Does not close the correct stream). Looking into this more

**Comment by dilanSachi** [comment]
The reason for the test failure is still being identified. Once it is identified and fixed, will create a new PR with the changes.

**Comment by dilanSachi** [comment]
The issue was that ballerina `http` does not propogate the stream reset event to the server and this makes the tests hang. This is fixed in https://github.com/ballerina-platform/module-ballerina-http/pull/659 and this PR is continued in https://github.com/ballerina-platform/module-ballerina-grpc/pull/444

**Pull request closed without merging**
