### PR TITLE
Fix protobuf package related issues in gRPC tool

### PR DESCRIPTION
**Pull request by MadhukaHarith92**
## Purpose
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1830
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1831
## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [x] Added tests

### CODE REVIEW

**Comment by daneshk** [comment]
@MadhukaHarith92 seems like this is a breaking change. Below client code will break, right?

```
stream<string, grpc:Error?> result = check ep->lotsOfReplies("WSO2");
```

**Comment by MadhukaHarith92** [comment]
> @MadhukaHarith92 seems like this is a breaking change. Below client code will break, right?
> 
> ```
> stream<string, grpc:Error?> result = check ep->lotsOfReplies("WSO2");
> ```

Yes, it seems the return params of these 2 functions have to be changed (`stream<string, grpc:Error?>` -> `stream<string, error?>`).
```
isolated remote function lotsOfReplies(string|ContextString req) returns stream<string, grpc:Error?>|grpc:Error {
        map<string|string[]> headers = {};
        string message;
        if req is ContextString {
            message = req.content;
            headers = req.headers;
        } else {
            message = req;
        }
        var payload = check self.grpcClient->executeServerStreaming("grpcservices.HelloWorld45/lotsOfReplies", message, headers);
        [stream<anydata, grpc:Error?>, map<string|string[]>] [result, _] = payload;
        StringStream outputStream = new StringStream(result);
        return new stream<string, grpc:Error?>(outputStream);
    }

    isolated remote function lotsOfRepliesContext(string|ContextString req) returns ContextStringStream|grpc:Error {
        map<string|string[]> headers = {};
        string message;
        if req is ContextString {
            message = req.content;
            headers = req.headers;
        } else {
            message = req;
        }
        var payload = check self.grpcClient->executeServerStreaming("grpcservices.HelloWorld45/lotsOfReplies", message, headers);
        [stream<anydata, grpc:Error?>, map<string|string[]>] [result, respHeaders] = payload;
        StringStream outputStream = new StringStream(result);
        return {content: new stream<string, grpc:Error?>(outputStream), headers: respHeaders};
    }
```

**Comment by BuddhiWathsala** [comment]
IMO, this breaking change is not a necessity. I think we shouldn’t ship such a breaking change to the upcoming releases.

**Comment by dilanSachi** [comment]
> IMO, this breaking change is not a necessity. I think we shouldn’t ship such a breaking change to the upcoming releases.

The protobuf stream definitions returns `error` instead of `grpc:Error`[1]. How do we handle this without this change?

[1] https://github.com/ballerina-platform/module-ballerina-protobuf/blob/0effb0811570881a5dff6c3bed01654ec0f1acf9/ballerina/modules/types.wrappers/string.bal#L31

**Comment by BuddhiWathsala** [comment]
According to this comment https://github.com/ballerina-platform/ballerina-standard-library/issues/1679#issuecomment-891719668,  the casting of `error -> grpc:Error` happens without any issue. So, this won’t be a problem, right?. @MadhukaHarith92

**Comment by dilanSachi** [comment]
> According to this comment [ballerina-platform/ballerina-standard-library#1679 (comment)](https://github.com/ballerina-platform/ballerina-standard-library/issues/1679#issuecomment-891719668), the casting of `error -> grpc:Error` happens without any issue. So, this won’t be a problem, right?. @MadhukaHarith92

When I generated the stub file and compile, the following error appears,
```
incompatible types: expected '(record {| map<anydata> value; |}|ballerina/grpc:1.0.0:Error)?', found '(record {| map<anydata> value; |}|error)?'
```

**Comment by MadhukaHarith92** [comment]
> According to this comment [ballerina-platform/ballerina-standard-library#1679 (comment)](https://github.com/ballerina-platform/ballerina-standard-library/issues/1679#issuecomment-891719668), the casting of `error -> grpc:Error` happens without any issue. So, this won’t be a problem, right?. @MadhukaHarith92

Yes, when testing the BBE, I had changed `stream<string, grpc:Error?> result = check ep->lotsOfReplies("WSO2");` -> `stream<string, error?> result = check ep->lotsOfReplies("WSO2");` in the client. Therefore, it had worked without any problem.

**Comment by MadhukaHarith92** [comment]
Closing in favor of https://github.com/ballerina-platform/module-ballerina-grpc/pull/409

**Pull request closed without merging**
